job_name: 'A3C for Self-play MyPong'
env: 'Pong-2p-v0'
agent: 'a3c'
learning_rate: 0.0001
discount: 0.99
t_max: 20
num_processes: 4
num_episodes_per_process: 2001
init_model_path: '' #checkpoints_selfplay\agent.model-900
checkpoint_freq: 100
checkpoint_dir: ''
use_atari_wrapper: True
monitor_dir: 'Selfplay2000-vs-selfplay900-Monitoring'
