job_name: 'A3C for Self-play MyPong'
env: 'Pong-2p-v0'
agent: 'a3c'
learning_rate: 0.0001
discount: 0.99
t_max: 20
num_processes: 4
num_episodes_per_process: 1001
init_model_path: '' #'checkpoints_selfplay_2\agent.model-2000'
checkpoint_freq: 20
checkpoint_dir: '' #'checkpoints_selfplay_powerup'
use_atari_wrapper: True
monitor_dir: 'SelfplayPowerup-vs-A3C10000-Monitoring'
