job_name: 'A3C for MyPong'
env: 'Pong-1p-v0'
agent: 'a3c'
learning_rate: 0.0001
discount: 0.99
t_max: 20
num_processes: 4
num_episodes_per_process: 10000
init_model_path: ''
checkpoint_freq: 100
checkpoint_dir: 'checkpoints'
use_atari_wrapper: True
monitor_dir: 'Training-monitoring'
